const UI_TEXT_CONFIG = [
  { id: 'MAIN_TITLE', text: 'HealtyPro' },
  { id: 'NAV_PLANNER', text: 'Planner' },
  { id: 'NAV_LIBRARY', text: 'Libreria' },
  { id: 'NAV_PROGRESS', text: 'Biometria' },
  { id: 'NAV_CHARTS', text: 'Grafici' },
  { id: 'NAV_RECIPES', text: 'Ricette' },
  { id: 'NAV_PROFILE', text: 'Profilo' },
  { id: 'NAV_GOALS', text: 'Obiettivi' },
  { id: 'LOAD_BUTTON', text: 'Carica' },
  { id: 'COPY_WEEK_BTN', text: 'Copia Settimana' },
  { id: 'RESET_BUTTON', text: 'Pulisci Settimana' },
  { id: 'BACKUP_BTN', text: 'Salva Backup' },
  { id: 'RESTORE_BTN', text: 'Ripristina Backup' },
  { id: 'CONFIG_URL_EMPTY_ERROR', text: 'Per favore, inserisci un URL.' },
  { id: 'CONFIG_LOAD_SUCCESS', text: 'Configurazione caricata!' },
  { id: 'COPY_WEEK_CONFIRM_TITLE', text: 'Copia Settimana' },
  { id: 'COPY_WEEK_CONFIRM_MSG', text: 'Sei sicuro di voler sovrascrivere il piano di questa settimana con quello della settimana precedente?' },
  { id: 'COPY_WEEK_SUCCESS', text: 'Piano settimanale copiato!' },
  { id: 'RESET_WEEK_CONFIRM_TITLE', text: 'Pulisci Settimana' },
  { id: 'RESET_WEEK_CONFIRM_MSG', text: 'Sei sicuro di voler cancellare tutti i pasti e gli allenamenti da questa settimana? L\'azione è irreversibile.' },
  { id: 'RESET_WEEK_SUCCESS', text: 'Settimana pulita!' },
  { id: 'SHARE_NO_URL_INFO', text: 'Nessun URL di configurazione da condividere.' },
  { id: 'SHARE_SUCCESS', text: 'Link di condivisione copiato!' },
  { id: 'SHARE_ERROR', text: 'Impossibile copiare il link.' },
  { id: 'BACKUP_SHARE_TITLE', text: 'Backup Dati HealtyPro' },
  { id: 'BACKUP_SUCCESS', text: 'Backup salvato con successo!' },
  { id: 'RESTORE_CONFIRM_TITLE', text: 'Ripristina Backup' },
  { id: 'RESTORE_CONFIRM_MSG', text: 'Sei sicuro di voler sovrascrivere la configurazione e il piano attuali? L\'azione è irreversibile.' },
  { id: 'RESTORE_SUCCESS', text: 'Backup ripristinato con successo!' },
  { id: 'RESTORE_INVALID_FILE', text: 'File di backup non valido o corrotto.' },
  { id: 'LOG_VIEW_EMPTY', text: 'Nessun pasto pianificato per questa settimana.' },
  { id: 'LOG_VIEW_WORKOUT_TITLE', text: 'Allenamento del Giorno' },
  { id: 'CONFIRM_MODAL_CONFIRM_BTN', text: 'Conferma' },
  { id: 'CONFIRM_MODAL_CANCEL_BTN', text: 'Annulla' },
  { id: 'LOAD_SHARED_CONFIG_TITLE', text: 'Caricare Nuova Configurazione?' },
  { id: 'LOAD_SHARED_CONFIG_MSG', text: 'Hai aperto un link di condivisione. Vuoi caricare questa nuova configurazione? La libreria di pasti attuale verrà sostituita.' },
  { id: 'BIOMETRICS_FORM_TITLE', text: 'Inserisci Misurazione' },
  { id: 'BIOMETRICS_HISTORY_TITLE', text: 'Storico Misurazioni' },
  { id: 'BIOMETRICS_SAVE_BTN', text: 'Salva Dati' },
  { id: 'BIOMETRICS_CLEAR_BTN', text: 'Annulla' },
  { id: 'BIOMETRICS_SAVE_SUCCESS', text: 'Dati biometrici salvati!' },
  { id: 'BIOMETRICS_DELETE_CONFIRM_TITLE', text: 'Elimina Misurazione' },
  { id: 'BIOMETRICS_DELETE_CONFIRM_MSG', text: 'Sei sicuro di voler eliminare i dati di questa data? L\'azione è irreversibile.' },
  { id: 'BIOMETRICS_DELETE_SUCCESS', text: 'Misurazione eliminata.' },
  { id: 'DELETE_WORKOUT_CONFIRM_TITLE', text: 'Elimina Allenamento' },
  { id: 'DELETE_WORKOUT_CONFIRM_MSG', text: 'Sei sicuro di voler eliminare questo allenamento dallo storico? L\'azione è irreversibile.' },
  { id: 'DELETE_WORKOUT_SUCCESS', text: 'Allenamento eliminato dallo storico.' },
  { id: 'BIOMETRICS_BMR_PLACEHOLDER', text: 'Completa il profilo per il calcolo' },
  { id: 'BIOMETRICS_EMPTY_LIST', text: 'Nessuna misurazione ancora registrata.' },
  { id: 'PROFILE_FORM_TITLE', text: 'Profilo Utente' },
  { id: 'PROFILE_SAVE_BTN', text: 'Salva Profilo' },
  { id: 'PROFILE_SAVE_SUCCESS', text: 'Profilo salvato con successo!' },
  { id: 'INFO_MODAL_TITLE', text: 'Formato `config.json` Richiesto' },
  { id: 'INFO_MODAL_DESC', text: 'Includi `calories_min` per ogni pasto. `calories_max` è opzionale.' },
  { id: 'SELECT_MEAL_TITLE', text: 'Scegli' },
  { id: 'NO_MEALS_AVAILABLE', text: 'Nessun pasto di questo tipo disponibile.' },
  { id: 'KCAL_LABEL', text: 'Kcal' },
  { id: 'EDITOR_MODAL_TITLE_PREFIX', text: 'Editor:' },
  { id: 'ADD_MEAL_BTN', text: 'Aggiungi Pasto' },
  { id: 'ADD_EXERCISE_BTN', text: 'Aggiungi Esercizio' },
  { id: 'LOG_ACTIVITY_BTN', text: 'Log Attività' },
  { id: 'MANAGE_WORKOUT_BTN', text: 'Gestisci' },
  { id: 'START_WORKOUT_BTN', text: 'Avvia Allenamento' },
  { id: 'WORKOUT_EDITOR_TITLE', text: 'Editor Allenamento' },
  { id: 'EXERCISE_EDITOR_TITLE', text: 'Modifica Esercizio' },
  { id: 'EXERCISE_SAVE_BTN', text: 'Salva Modifiche' },
  { id: 'EXERCISE_TEMPO_HOLD_LABEL', text: 'Tenuta (s)' },
  { id: 'EXERCISE_WEIGHT_LABEL', text: 'Peso (kg)' },
  { id: 'SELECT_EXERCISE_TITLE', text: 'Scegli Esercizio' },
  { id: 'NO_WORKOUTS_AVAILABLE', text: 'Nessun esercizio disponibile. Controlla il file esercizi.json.' },
  { id: 'RECIPE_BUTTON_TITLE', text: 'Mostra ricetta' },
  { id: 'RECIPE_MODAL_LOADING', text: 'Caricamento ricetta...' },
  { id: 'RECIPE_MODAL_LOAD_ERROR', text: 'Impossibile caricare la ricetta. Controlla l\'URL e la connessione.' },
  { id: 'RECIPE_LOAD_FAIL_MSG', text: 'Caricamento ricetta fallito' },
  { id: 'INFO_MODAL_EXAMPLE_JSON', text: '{\n  "rules": [],\n  "meals": []\n}' },
  { id: 'CHARTS_TITLE', text: 'Dashboard Grafici' },
  { id: 'PLANNER_CHART_TITLE', text: 'Riepilogo Calorie Settimanali' },
  { id: 'BIOMETRICS_CHART_TITLE', text: 'Andamento Dati Biometrici' },
  { id: 'CHARTS_CORRELATION_TITLE', text: 'Correlazione Peso e Calorie' },
  { id: 'VELOCITY_CHART_TITLE', text: 'Andamento Variazione Peso' },
  { id: 'BIOMETRICS_CHART_EMPTY', text: 'Inserisci almeno due misurazioni per visualizzare il grafico.' },
  { id: 'RECIPES_TITLE', text: 'Tutte le Ricette' },
  { id: 'RECIPES_EMPTY', text: 'Nessuna ricetta disponibile. Carica una configurazione che includa pasti con `recipeId`.' },
  { id: 'TRAINER_REST_LABEL', text: 'RECUPERO' },
  { id: 'TRAINER_PAUSED_LABEL', text: 'PAUSA' },
  { id: 'TRAINER_REP_LABEL', text: 'Rip.' },
  { id: 'TRAINER_UPCOMING_LABEL', text: 'A seguire:' },
  { id: 'API_FETCH_ERROR', text: 'Errore di rete caricando' },
  { id: 'API_INVALID_JSON', text: 'Errore nel formato di un file di configurazione. Controlla la console se il debug è attivo.' },
  { id: 'API_INVALID_MEALS_FILE', text: 'Il file dei pasti non è valido. Manca la chiave \'meals\' o non è un array.' },
  { id: 'API_INVALID_INGREDIENTS_FILE', text: 'Il file degli ingredienti non è valido. Manca la chiave \'ingredienti\' o non è un array.' },
  { id: 'API_EXERCISES_FILE_WARN', text: 'File esercizi.json non trovato o non valido. Continuo senza dati di allenamento.' },
  { id: 'API_CONFIG_LOAD_FAIL', text: 'Impossibile caricare la configurazione completa. Controlla la console.' },
  { id: 'CHART_KCAL_MIN_LABEL', text: 'Kcal Min' },
  { id: 'CHART_KCAL_MAX_LABEL', text: 'Kcal Max' },
  { id: 'CHART_KCAL_RANGE_LABEL', text: 'Kcal (Min-Max)' },
  { id: 'CHART_BAR_VIEW_BTN', text: 'Barre' },
  { id: 'CHART_LINE_VIEW_BTN', text: 'Linee' },
  { id: 'BIOMETRICS_EDIT_BTN', text: 'Modifica' },
  { id: 'BIOMETRICS_DELETE_BTN', text: 'Elimina' },
  { id: 'BIOMETRICS_ACTIONS_TITLE', text: 'Azioni' },
  { id: 'IMPORT_BIOMETRICS_BTN', text: 'Importa CSV' },
  { id: 'IMPORT_SUCCESS', text: 'Dati importati con successo!' },
  { id: 'IMPORT_CONFIRM_TITLE', text: 'Importa Dati Biometrici' },
  { id: 'IMPORT_NO_NEW_DATA', text: 'Nessuna nuova misurazione trovata nel file.' },
  { id: 'IMPORT_ERROR_FILE', text: 'Errore durante la lettura del file.' },
  { id: 'IMPORT_ERROR_FORMAT', text: 'Formato del file CSV non riconosciuto.' },
  { id: 'PLANNER_EXERCISES_SINGLE_LABEL', text: 'esercizio' },
  { id: 'PLANNER_EXERCISES_MULTI_LABEL', text: 'esercizi' },
  { id: 'TRAINER_SET_LABEL', text: 'Serie' },
  { id: 'TRAINER_OF_SETS_LABEL', text: 'di' },
  { id: 'TRAINER_REPS_LABEL', text: 'Ripetizioni' },
  { id: 'TRAINER_MANUAL_REP_BTN_LABEL', text: 'REGISTRA REP' },
  { id: 'TRAINER_MANUAL_REPS_LABEL', text: 'Ripetizioni' },
  { id: 'DEBRIEFING_TITLE', text: 'Riepilogo Allenamento' },
  { id: 'DEBRIEFING_BACK_BTN', text: 'Torna al Planner' },
  { id: 'DEBRIEFING_NO_SUMMARY', text: 'Nessun riepilogo dell\'allenamento disponibile.' },
  { id: 'DEBRIEFING_COMPLETED', text: 'Completato' },
  { id: 'DEBRIEFING_INCOMPLETE', text: 'Incompleto' },
  { id: 'DEBRIEFING_SETS_COMPLETED', text: 'Serie completate' },
  { id: 'DEBRIEFING_TONNAGE', text: 'Tonnellaggio' },
  { id: 'DEBRIEFING_STATS_TITLE', text: 'Statistiche Finali' },
  { id: 'DEBRIEFING_TOTAL_TIME', text: 'Tempo Totale' },
  { id: 'DEBRIEFING_EXERCISE_TIME', text: 'Tempo di Lavoro' },
  { id: 'DEBRIEFING_REST_TIME', text: 'Tempo di Recupero' },
  { id: 'DEBRIEFING_CALORIES_BURNED', text: 'Calorie Bruciate' },
  { id: 'DEBRIEFING_SET_LABEL', text: 'Serie' },
  { id: 'DEBRIEFING_RPE_LABEL', text: 'Sforzo Percepito (RPE 1-10)' },
  { id: 'DEBRIEFING_SAVE_RPE_BTN', text: 'Salva RPE' },
  { id: 'DEBRIEFING_SUMMARY_AUDIO_BTN', text: 'Ascolta Riepilogo' },
  { id: 'PLANNER_SUMMARY_TITLE', text: 'Riepilogo Settimanale' },
  { id: 'PLANNER_SUMMARY_AVG_KCAL', text: 'Media Kcal/giorno' },
  { id: 'PLANNER_SUMMARY_WORKOUTS', text: 'Allenamenti' },
  { id: 'PLANNER_SUMMARY_CALORIES_BURNED', text: 'Kcal Bruciate' },
  { id: 'PLANNER_SUMMARY_WEIGHT_PROGRESS', text: 'Kg mancanti' },
  { id: 'MANUAL_WORKOUT_MODAL_TITLE', text: 'Registra Attività Manuale' },
  { id: 'MANUAL_WORKOUT_NAME_LABEL', text: 'Nome Attività' },
  { id: 'MANUAL_WORKOUT_DURATION_LABEL', text: 'Durata' },
  { id: 'MANUAL_WORKOUT_DISTANCE_LABEL', text: 'Distanza (km)' },
  { id: 'MANUAL_WORKOUT_FC_AVG_LABEL', text: 'FC Media (bpm)' },
  { id: 'MANUAL_WORKOUT_FC_MAX_LABEL', text: 'FC Max (bpm)' },
  { id: 'MANUAL_WORKOUT_NOTES_LABEL', text: 'Note' },
  { id: 'MANUAL_WORKOUT_SAVE_BTN', text: 'Salva Attività' },
  { id: 'LOG_VIEW_MANUAL_ACTIVITY_TITLE', text: 'Attività del Giorno' },
  { id: 'GOALS_TITLE', text: 'Obiettivi Settimanali' },
  { id: 'GOALS_SAVE_BTN', text: 'Salva Obiettivi' },
  { id: 'GOALS_SAVE_SUCCESS', text: 'Obiettivi salvati!' },
  { id: 'GOALS_EXPLANATION', text: 'Imposta i tuoi obiettivi settimanali per monitorare i progressi. Questi dati verranno visualizzati nel riepilogo del planner per tenerti motivato.' },
  { id: 'GOALS_ACTIVITY_LEGEND', text: 'Attività Fisica' },
  { id: 'GOALS_BIOMETRICS_LEGEND', text: 'Dati Biometrici' },
  { id: 'GOAL_CALORIES_LABEL', text: 'Obiettivo Calorico Medio Giornaliero' },
  { id: 'GOAL_WORKOUTS_LABEL', text: 'Obiettivo Allenamenti a Settimana' },
  { id: 'GOAL_WEIGHT_LABEL', text: 'Obiettivo Peso (kg)' },
  { id: 'WORKOUT_LOG_SAVE_SUCCESS', text: 'Allenamento aggiornato con successo!' },
  { id: 'LOGGED_EXERCISE_EDITOR_TITLE', text: 'Modifica Esercizio Registrato' },
  { id: 'LOGGED_EXERCISE_SET_LABEL', text: 'Set' },
  { id: 'LOGGED_EXERCISE_REPS_LABEL', text: 'Reps' },
  { id: 'LOGGED_EXERCISE_WEIGHT_LABEL', text: 'Peso' },
  { id: 'LOGGED_EXERCISE_SAVE_BTN', text: 'Salva Modifiche Esercizio' },
  { id: 'VOICE_GUIDE_WORKOUT_START', text: 'Allenamento iniziato' },
  { id: 'VOICE_GUIDE_NOW_STARTING', text: 'Inizio con' },
  { id: 'VOICE_GUIDE_NEXT_EXERCISE', text: 'Prossimo esercizio' },
  { id: 'VOICE_GUIDE_REST_START', text: 'Recupero' },
  { id: 'VOICE_GUIDE_SET_START', text: 'Inizio' },
  { id: 'VOICE_GUIDE_PHASE_UP', text: 'su' },
  { id: 'VOICE_GUIDE_PHASE_HOLD', text: 'tieni' },
  { id: 'VOICE_GUIDE_PHASE_DOWN', text: 'giù' },
  { id: 'VOICE_GUIDE_WORKOUT_COMPLETED', text: 'Allenamento completato' },
  { id: 'TERMINATE_WORKOUT_CONFIRM_TITLE', text: 'Termina Allenamento' },
  { id: 'TERMINATE_WORKOUT_CONFIRM_MSG', text: 'Sei sicuro di voler terminare l\'allenamento? I progressi verranno salvati.' },
  { id: 'TERMINATE_WORKOUT_PROMPT_MSG', text: 'Vuoi salvare i progressi o scartare completamente questo allenamento?' },
  { id: 'SAVE_AND_END_BTN', text: 'Salva e Termina' },
  { id: 'DISCARD_WORKOUT_BTN', text: 'Scarta Allenamento' },
  { id: 'DISCARD_WORKOUT_CONFIRM_TITLE', text: 'Scartare Allenamento?' },
  { id: 'DISCARD_WORKOUT_CONFIRM_MSG', text: 'L\'allenamento non verrà salvato nello storico. Questa azione è irreversibile.' },
  { id: 'CHARTS_GOAL_ESTIMATE_LABEL', text: 'Settimane stimate all\'obiettivo' },
  { id: 'CHARTS_GOAL_ESTIMATE_NOT_SET', text: 'Imposta un obiettivo di peso' }
];

export const UI_TEXT = UI_TEXT_CONFIG.reduce((acc, { id, text }) => {
  acc[id] = text;
  return acc;
}, {});
